### ISSUE TITLE
Plain slow zlib is used despite zlib-ng and zlib-rs being requested

### ISSUE THREAD

**Issue by Shnatsel** [fintelia/corpus-bench#3]
Not even zlib-ng, just plain zlib, which shows as 3x lower performance than zlib-ng. Here's the profile showing the C code being reached: https://share.firefox.dev/4fTJ2Oy 

Profiling attributes the code to libz-sys-1.1.20, but flate2 doesn't even depend on that:

```
flate2 v1.0.35
├── crc32fast v1.4.2
│   └── cfg-if v1.0.0
├── libz-rs-sys v0.4.0
│   └── zlib-rs v0.4.0
└── miniz_oxide v0.8.0
    ├── adler2 v2.0.0
    └── simd-adler32 v0.3.7
```

But we do have libz-sys in the dependency tree:

```
cargo tree -i libz-sys
libz-sys v1.1.20
├── mtpng v0.3.5
│   └── corpus-bench v0.1.0 (/home/shnatsel/Code/corpus-bench)
└── spng-sys v0.1.0
    └── spng v0.1.0
        └── corpus-bench v0.1.0 (/home/shnatsel/Code/corpus-bench)
```

This must be C linking rearing its ugly head and not allowing multiple versions of the same library (zlib) to be present.

If I configure `flate2` with `zlib-ng` feature instead of `zlib-rs`, performance shoots up 3x, so at least selecting zlib-ng must be working. I suspect that's because we're using `zlib-ng` rather than `zlib-ng-compat` which presents a different library name, and so doesn't clash with zlib.

**Comment by Shnatsel** [comment]
Removing the `mtpng` dependency and switching `flate2` back to default features fixes that. 
Not 100% sure yet if flate2 switch is actually needed.

**Comment by fintelia** [comment]
Thanks for tracking this down!
